name: primecount CI tests

on: [push, pull_request]

jobs:
  windows_mingw64_x64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          install: base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake
      - name: Build primecount
        run: |
            cmake . -G "Unix Makefiles"
            grep "^OpenMP:INTERNAL=1$" CMakeCache.txt
            grep "^int128.*:INTERNAL=1$" CMakeCache.txt
            grep "^cpu_supports_popcnt:INTERNAL=1$" CMakeCache.txt
            grep "^libdivide_branchfree:INTERNAL=1$" CMakeCache.txt
            make -j2
      - name: CTest (unit tests)
        run: ctest -j2
      - name: primecount --test option
        run: ./primecount --test

  linux_x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install valgrind
        run: |
            sudo apt update
            sudo apt install valgrind
      - name: Build primecount
        run: |
            cmake .
            grep "^OpenMP:INTERNAL=1$" CMakeCache.txt
            grep "^int128.*:INTERNAL=1$" CMakeCache.txt
            grep "^cpu_supports_popcnt:INTERNAL=1$" CMakeCache.txt
            grep "^libdivide_branchfree:INTERNAL=1$" CMakeCache.txt
            make -j2
      - name: CTest (unit tests)
        run: ctest -j2
      - name: primecount --test option
        run: ./primecount --test
      - name: Valgrind legendre test
        run: valgrind --error-exitcode=1 ./primecount 1e11 --legendre
      - name: Valgrind meissel test
        run: valgrind --error-exitcode=1 ./primecount 1e11 --meissel
      - name: Valgrind lehmer test
        run: valgrind --error-exitcode=1 ./primecount 1e11 --lehmer
      - name: Valgrind lmo test
        run: valgrind --error-exitcode=1 ./primecount 1e11 --lmo
      - name: Valgrind deleglise-rivat test
        run: valgrind --error-exitcode=1 ./primecount 1e13 --deleglise-rivat
      - name: Valgrind gourdon test
        run: valgrind --error-exitcode=1 ./primecount 1e14 --gourdon
      - name: PrimePi(1e20) 128-bit test
        run: |
            ./primecount 1e20 -s | tee primecount-1e20.log
            grep 2220819602560918840 primecount-1e20.log
